/**
 * Test Client for OurBank Microservices Application
 *
 * This client tests all communication protocols:
 * - REST API (CRUD operations)
 * - GraphQL API (flexible queries)
 */

const BASE_URL = process.env.API_URL || 'http://localhost:3000';

// ========================
// Helper: HTTP request
// ========================

async function request(method, url, body = null) {
  const options = {
    method,
    headers: { 'Content-Type': 'application/json' }
  };
  if (body) {
    options.body = JSON.stringify(body);
  }
  const response = await fetch(`${BASE_URL}${url}`, options);
  const data = await response.json();
  return { status: response.status, data };
}

// ========================
// Test: REST API
// ========================

async function testREST() {
  console.log('\n========================================');
  console.log('  Testing REST API');
  console.log('========================================\n');

  let customerId, accountId;

  // 1. Create a customer
  console.log('1. Creating a customer...');
  const createRes = await request('POST', '/api/customers', {
    first_name: 'Ahmed',
    last_name: 'Ben Ali',
    email: `ahmed.benali${Date.now()}@example.com`,
    phone: '+216 55 123 456',
    address: '123 Rue Habib Bourguiba, Tunis'
  });
  console.log('   Status:', createRes.status);
  console.log('   Customer:', JSON.stringify(createRes.data, null, 2));
  customerId = createRes.data.id;

  // 2. Get customer
  console.log('\n2. Getting customer by ID...');
  const getRes = await request('GET', `/api/customers/${customerId}`);
  console.log('   Status:', getRes.status);
  console.log('   Customer:', getRes.data.first_name, getRes.data.last_name);

  // 3. Update customer
  console.log('\n3. Updating customer...');
  const updateRes = await request('PUT', `/api/customers/${customerId}`, {
    phone: '+216 55 999 888',
    address: '456 Avenue Mohamed V, Tunis'
  });
  console.log('   Status:', updateRes.status);
  console.log('   Updated phone:', updateRes.data.phone);

  // 4. List customers
  console.log('\n4. Listing customers...');
  const listRes = await request('GET', '/api/customers');
  console.log('   Status:', listRes.status);
  console.log('   Total customers:', listRes.data.total);

  // 5. Search customers
  console.log('\n5. Searching customers by name...');
  const searchRes = await request('GET', '/api/customers/search/Ahmed');
  console.log('   Status:', searchRes.status);
  console.log('   Found:', searchRes.data.total, 'result(s)');

  // 6. Create an account
  console.log('\n6. Creating a bank account...');
  const accountRes = await request('POST', '/api/accounts', {
    customer_id: customerId,
    account_type: 'CHECKING',
    currency: 'TND',
    initial_balance: 5000
  });
  console.log('   Status:', accountRes.status);
  console.log('   Account:', JSON.stringify(accountRes.data, null, 2));
  accountId = accountRes.data.id;

  // 7. Get account balance
  console.log('\n7. Checking account balance...');
  const balanceRes = await request('GET', `/api/accounts/${accountId}/balance`);
  console.log('   Status:', balanceRes.status);
  console.log('   Balance:', balanceRes.data.balance, balanceRes.data.currency);

  // 8. Create a deposit transaction
  console.log('\n8. Creating a deposit transaction...');
  const depositRes = await request('POST', '/api/transactions', {
    account_id: accountId,
    transaction_type: 'DEPOSIT',
    amount: 1500,
    currency: 'TND',
    description: 'Salary deposit'
  });
  console.log('   Status:', depositRes.status);
  console.log('   Transaction:', depositRes.data.transaction_type, depositRes.data.amount);

  // 9. Create a withdrawal transaction
  console.log('\n9. Creating a withdrawal transaction...');
  const withdrawRes = await request('POST', '/api/transactions', {
    account_id: accountId,
    transaction_type: 'WITHDRAWAL',
    amount: 200,
    currency: 'TND',
    description: 'ATM withdrawal'
  });
  console.log('   Status:', withdrawRes.status);
  console.log('   Transaction:', withdrawRes.data.transaction_type, withdrawRes.data.amount);

  // 10. List transactions
  console.log('\n10. Listing transactions for account...');
  const txListRes = await request('GET', `/api/accounts/${accountId}/transactions`);
  console.log('   Status:', txListRes.status);
  console.log('   Total transactions:', txListRes.data.total);

  // 11. Check updated balance
  console.log('\n11. Checking updated balance...');
  const newBalanceRes = await request('GET', `/api/accounts/${accountId}/balance`);
  console.log('   Balance:', newBalanceRes.data.balance, newBalanceRes.data.currency);

  // 12. List notifications (generated by Kafka events)
  console.log('\n12. Listing notifications (async - may take a moment)...');
  await new Promise(resolve => setTimeout(resolve, 2000));
  const notifRes = await request('GET', `/api/notifications?customer_id=${customerId}`);
  console.log('   Status:', notifRes.status);
  console.log('   Total notifications:', notifRes.data.total);
  if (notifRes.data.notifications) {
    notifRes.data.notifications.forEach(n => {
      console.log(`   - [${n.type}] ${n.title}: ${n.message}`);
    });
  }

  // 13. Health check
  console.log('\n13. Health check...');
  const healthRes = await request('GET', '/api/health');
  console.log('   Status:', healthRes.status);
  console.log('   Health:', JSON.stringify(healthRes.data, null, 2));

  // 14. Delete customer (cleanup)
  console.log('\n14. Deleting customer...');
  const deleteRes = await request('DELETE', `/api/customers/${customerId}`);
  console.log('   Status:', deleteRes.status);
  console.log('   Result:', deleteRes.data.message);

  return { customerId, accountId };
}

// ========================
// Test: GraphQL API
// ========================

async function testGraphQL() {
  console.log('\n========================================');
  console.log('  Testing GraphQL API');
  console.log('========================================\n');

  const createRes = await request('POST', '/api/customers', {
    first_name: 'Fatma',
    last_name: 'Trabelsi',
    email: `fatma.trabelsi${Date.now()}@example.com`,
    phone: '+216 22 456 789',
    address: '789 Rue de la Liberté, Sfax'
  });
  const customerId = createRes.data.id;

  const accountRes = await request('POST', '/api/accounts', {
    customer_id: customerId,
    account_type: 'SAVINGS',
    currency: 'TND',
    initial_balance: 10000
  });
  const accountId = accountRes.data.id;

  // 1. GraphQL: Get customer
  console.log('1. GraphQL Query - Get customer by ID...');
  const gql1 = await graphqlRequest(`
    query {
      customer(id: "${customerId}") {
        id
        first_name
        last_name
        email
      }
    }
  `);
  console.log('   Result:', JSON.stringify(gql1.data, null, 2));

  // 2. GraphQL: List customers
  console.log('\n2. GraphQL Query - List customers...');
  const gql2 = await graphqlRequest(`
    query {
      customers(page: 1, limit: 5) {
        customers {
          id
          first_name
          last_name
          email
        }
        total
      }
    }
  `);
  console.log('   Total:', gql2.data?.customers?.total);

  // 3. GraphQL: Customer with accounts and notifications
  console.log('\n3. GraphQL Query - Customer with accounts and notifications...');
  const gql3 = await graphqlRequest(`
    query {
      customerWithDetails(id: "${customerId}") {
        customer {
          id
          first_name
          last_name
          email
        }
        accounts {
          id
          account_type
          balance
          currency
        }
        notifications {
          id
          type
          title
          read
        }
      }
    }
  `);
  console.log('   Result:', JSON.stringify(gql3.data, null, 2));

  // 4. GraphQL: Get account with customer info
  console.log('\n4. GraphQL Query - Account with customer info...');
  const gql4 = await graphqlRequest(`
    query {
      account(id: "${accountId}") {
        id
        account_type
        balance
        currency
        customer {
          first_name
          last_name
          email
        }
      }
    }
  `);
  console.log('   Result:', JSON.stringify(gql4.data, null, 2));

  // 5. GraphQL: Search customers
  console.log('\n5. GraphQL Query - Search customers...');
  const gql5 = await graphqlRequest(`
    query {
      searchCustomers(query: "Fatma") {
        customers {
          id
          first_name
          last_name
        }
        total
      }
    }
  `);
  console.log('   Found:', gql5.data?.searchCustomers?.total, 'result(s)');

  // 6. GraphQL: Create customer via mutation
  console.log('\n6. GraphQL Mutation - Create customer...');
  const gql6 = await graphqlRequest(`
    mutation {
      createCustomer(input: {
        first_name: "Mohamed",
        last_name: "Bouazizi",
        email: "mohamed.bouazizi${Date.now()}@example.com",
        phone: "+216 98 111 222"
      }) {
        id
        first_name
        last_name
        email
      }
    }
  `);
  console.log('   Created:', JSON.stringify(gql6.data, null, 2));

  // Cleanup
  await request('DELETE', `/api/customers/${customerId}`);

  return true;
}

// ========================
// GraphQL helper
// ========================

async function graphqlRequest(query) {
  try {
    const response = await fetch(`${BASE_URL}/graphql`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query })
    });
    return await response.json();
  } catch (error) {
    console.error('GraphQL request failed:', error.message);
    return { errors: [{ message: error.message }] };
  }
}

// ========================
// Main
// ========================

async function main() {
  console.log('==========================================');
  console.log('  OurBank Microservices - Test Client');
  console.log('==========================================');
  console.log(`  API URL: ${BASE_URL}`);
  console.log('==========================================');

  try {
    await testREST();
    await testGraphQL();

    console.log('\n==========================================');
    console.log('  All tests completed!');
    console.log('==========================================\n');
  } catch (error) {
    console.error('\nTest failed with error:', error.message);
    console.error('Make sure all services are running:');
    console.error('  - Customer Service (gRPC :50051)');
    console.error('  - Account Service (gRPC :50052)');
    console.error('  - Notification Service (gRPC :50053)');
    console.error('  - API Gateway (HTTP :3000)');
    console.error('  - Kafka (localhost:9092)');
  }
}

main();
